cozygames/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'cozygames'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('booking_table/', views.BookingTableView.as_view(), name='booking_table'),
    path('booking/cancel_bookings/', views.CancelReservation.as_view(), name='cancel_bookings'),
    path('booking/booking_history/', views.BookingHistoryView.as_view(), name='booking_history'),
    path('booking/voting/', views.VotingView.as_view(), name='voting'),
    path('booking/card_game_info/<int:game_id>/', views.CardGameInfoView.as_view(), name='card_game_info'),
]

cozygames_core/urls.py
from django.contrib import admin
from django.urls import path, include

from cozygames_core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cozygames.urls', namespace='booking')),
    path('users/', include('users.urls', namespace='user')),
    path('forum/', include('forum.urls', namespace='forum'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('themes/', views.ThemesView.as_view(), name='themes'),
    path('questions/<int:theme_id>', views.QuestionsView.as_view(), name='questions'),
    path('question_detail/<int:question_id>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('create_message/', views.CreateMessageView.as_view(), name='create_message'),
    path('create_question/', views.CreateQuestionView.as_view(), name='create_question'),

    path('client_reviews/', views.ClientReviewView.as_view(), name='client_reviews'),
    path('create_review/', views.CreateClientReviewView.as_view(), name='create_review'),

    path('blog/', views.BlogView.as_view(), name='blog'),

    path('tournaments/', views.TournamentsView.as_view(), name='tournaments'),
    path('tournament/<int:tournament_id>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('finished_tournaments/', views.FinishedTournamentsView.as_view(), name='finished_tournaments'),
    path('finished_tournament_detail/<int:tournament_id>/', views.FinishedTournamentDetailView.as_view(),
         name='finished_tournament_detail'),
    path('tournament/add/', views.AddParticipantView.as_view(), name='add_participant'),
    path('tournament/remove/', views.RemoveParticipantView.as_view(), name='remove_participant'),
    path('tournament/leave_tournament/', views.LeaveTournamentView.as_view(), name='leave_tournament'),
    path('tournament/create_tournament/', views.CreateTournamentView.as_view(), name='create_tournament'),
    path('tournament/my_tournaments/', views.MyTournamentsView.as_view(), name='my_tournaments'),
    path('tournament/participating_tournaments/', views.ParticipatingTournamentView.as_view(),
         name='participating_tournaments')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.RegisterUser.as_view(), name='registration'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

cozygames_core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}CozyGames{% endblock %}</title>
    <link rel="icon" href="{% static 'cozygames.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffa857;">
    <div class="container-fluid">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'users:profile' %}">{{ user.username }}</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'cozygames:index' %}">CozyGames</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'cozygames:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'users:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cozygames:booking' %}">Booking</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cozygames:voting' %}">Vote</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:tournaments' %}">Tournaments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:themes' %}">Forum</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:client_reviews' %}">Feedback</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <form action="{% url 'users:logout' %}?next={{ request.path }}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">
                            Logout
                        </button>
                    </form>
                    {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}?next={{ request.path }}">Sign in</a>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</nav>


{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} d-flex align-items-center" role="alert">
    <div class="container">
        <div class="row-1 d-flex justify-content-center">
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% block body %}
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
{% endblock %}

</body>
</html>