cozygames/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'cozygames'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('booking_table/', views.BookingTableView.as_view(), name='booking_table'),
    path('booking/cancel_bookings/', views.CancelReservation.as_view(), name='cancel_bookings'),
    path('booking/booking_history/', views.BookingHistoryView.as_view(), name='booking_history'),
    path('booking/voting/', views.VotingView.as_view(), name='voting'),
    path('booking/card_game_info/<int:game_id>/', views.CardGameInfoView.as_view(), name='card_game_info'),
]

cozygames_core/urls.py
from django.contrib import admin
from django.urls import path, include

from cozygames_core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cozygames.urls', namespace='booking')),
    path('users/', include('users.urls', namespace='user')),
    path('forum/', include('forum.urls', namespace='forum'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('themes/', views.ThemesView.as_view(), name='themes'),
    path('questions/<int:theme_id>', views.QuestionsView.as_view(), name='questions'),
    path('question_detail/<int:question_id>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('create_message/', views.CreateMessageView.as_view(), name='create_message'),
    path('create_question/', views.CreateQuestionView.as_view(), name='create_question'),

    path('client_reviews/', views.ClientReviewView.as_view(), name='client_reviews'),
    path('create_review/', views.CreateClientReviewView.as_view(), name='create_review'),

    path('blog/', views.BlogView.as_view(), name='blog'),

    path('tournaments/', views.TournamentsView.as_view(), name='tournaments'),
    path('tournament/<int:tournament_id>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('finished_tournaments/', views.FinishedTournamentsView.as_view(), name='finished_tournaments'),
    path('finished_tournament_detail/<int:tournament_id>/', views.FinishedTournamentDetailView.as_view(),
         name='finished_tournament_detail'),
    path('tournament/add/', views.AddParticipantView.as_view(), name='add_participant'),
    path('tournament/remove/', views.RemoveParticipantView.as_view(), name='remove_participant'),
    path('tournament/leave_tournament/', views.LeaveTournamentView.as_view(), name='leave_tournament'),
    path('tournament/create_tournament/', views.CreateTournamentView.as_view(), name='create_tournament'),
    path('tournament/my_tournaments/', views.MyTournamentsView.as_view(), name='my_tournaments'),
    path('tournament/participating_tournaments/', views.ParticipatingTournamentView.as_view(),
         name='participating_tournaments')
]

cozygames/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Table(models.Model):
    class Type(models.TextChoices):
        BOARD = "BG", _("board game")
        CONSOLE = "CG", _("console game")

    number: int = models.IntegerField(unique=True, blank=False, null=False, default=0)
    type: str = models.CharField(max_length=2, choices=Type, default=Type.BOARD)
    objects: QuerySet

    def __str__(self):
        return f"Table #{self.number}  {self.get_type_display()}"


class Reservation(models.Model):
    user: User = models.ForeignKey(User, related_name='reservations', on_delete=models.CASCADE)
    table: Table = models.ForeignKey(Table, related_name='reservations', on_delete=models.CASCADE)
    date = models.DateField(blank=False)
    objects: QuerySet

    def __str__(self):
        return f"Reservation of table #{self.table.number} on {self.date}"


class CardGame(models.Model):
    name = models.CharField(max_length=100, null=False)
    min_number_player = models.PositiveIntegerField(null=False, blank=False)
    max_number_player = models.PositiveIntegerField(null=False, blank=False)
    description = models.TextField(null=True, blank=True, default='No description.')
    objects: QuerySet

    def __str__(self):
        return f"{self.name}"


class Voting(models.Model):
    date = models.DateField(null=False, unique_for_date=True, auto_now=False, auto_now_add=True)
    result = models.ForeignKey(CardGame, related_name='votings', blank=True, null=True, default=None,
                               on_delete=models.SET_NULL)
    objects: QuerySet

    def __str__(self):
        return f"Voting of {self.date}"


class Vote(models.Model):
    user = models.ForeignKey(User, related_name='votes', null=True, blank=False, on_delete=models.SET_NULL)
    card_game = models.ForeignKey(CardGame, related_name='votes', null=False, blank=False, on_delete=models.CASCADE)
    voting = models.ForeignKey(Voting, related_name='votes', blank=False, null=False, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    objects: QuerySet

    def __str__(self):
        return f"Vote of {self.user} for {self.card_game.name} on {self.date}"

    class Meta:
        unique_together = ('user', 'date', 'card_game')

    @classmethod
    def user_can_vote(cls, user: User, date) -> bool:
        """Checks if the user can vote on the given date."""
        return cls.objects.filter(user=user, date=date).count() < 3

cozygames/forms.py
from django import forms
from django.utils import timezone

from cozygames.models import CardGame


class DateInput(forms.DateInput):
    input_type = 'date'


class BookingDateForm(forms.Form):
    """ Booking date form to choice a date in the calendar """

    date = forms.DateField(
        widget=DateInput(attrs={'min': timezone.datetime.today().strftime('%Y-%m-%d'),
                                'max': (timezone.datetime.today() + timezone.timedelta(days=10)).strftime('%Y-%m-%d')}),
        initial=timezone.datetime.today().strftime('%Y-%m-%d'))


class VotingForm(forms.Form):
    """Form for voting for a game."""
    game = forms.ModelChoiceField(queryset=CardGame.objects.all(), label='Select a game')

cozygames/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpRequest, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.views.decorators.cache import cache_page
from django.utils import timezone

from cozygames.forms import BookingDateForm, VotingForm
from cozygames.models import Table, Reservation, Vote, Voting, CardGame


# Create your views here.
class IndexView(generic.TemplateView):
    """ This is main page of the site """
    template_name = "cozygames/index.html"

    @method_decorator(cache_page(60 * 15))
    def get(self, *args, **kwargs):
        return super().get(self, *args, **kwargs)


class BookingView(generic.TemplateView):
    """ This page for booking tables """
    template_name = 'cozygames/booking.html'
    form_class = BookingDateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['form'] = self.form_class()
        context['tables'] = Table.objects.filter(~Q(reservations__date=today))
        context['date'] = today
        return context

    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)

    def post(self, *args, **kwargs):
        form = BookingDateForm(self.request.POST)
        context = {'form': form}
        if form.is_valid():
            date = form.cleaned_data['date']
            tables = Table.objects.filter(~Q(reservations__date=date))
            context['tables'] = tables
            context['date'] = date
        return render(self.request, 'cozygames/booking.html', context=context)


class BookingTableView(LoginRequiredMixin, View):
    model = Table

    def post(self, request: HttpRequest, *args, **kwargs):
        try:
            date = datetime.strptime(request.POST.get('date'), '%Y-%m-%d')
        except (TypeError, ValueError):
            messages.warning(request, f'Somthing wrong with date')
            return redirect(reverse('cozygames:booking'))
        days_delta = (date.date() - timezone.now().date()).days

        if days_delta > 10 or days_delta < 0:
            messages.warning(request, f"You cannot book earlier than today or more than 10 days in advance.")

        elif request.user.reservations.filter(date=date):
            messages.warning(request, "You already have reservation that day.")

        elif request.user.reservations.filter(date__gte=timezone.now().date()).count() > 2:
            messages.warning(request, "You cannot have more than 3 reservations at the same time.")

        else:
            table = get_object_or_404(self.model, id=request.POST['table_id'])
            Reservation.objects.create(user=request.user, date=date, table=table)
            messages.success(request, "The table has been successfully booked.")

        return redirect(reverse('cozygames:booking'))


class CancelReservation(LoginRequiredMixin, generic.list.MultipleObjectMixin, generic.View):
    model = Reservation
    context_object_name = 'reservations'
    template_name = 'cozygames/cancel_bookings.html'
    success_url = reverse_lazy('cozygames:cancel_bookings')

    def get_queryset(self):
        return self.request.user.reservations.filter(date__gte=timezone.now().date()).order_by(
            'date').select_related(
            'table')

    def get(self, request: HttpRequest, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data(object_list=self.get_queryset()))

    def post(self, request: HttpRequest, *args, **kwargs):
        reservation = request.user.reservations.filter(id=request.POST.get('reservation_id')).first()
        if reservation:
            reservation_date = reservation.date
            reservation.delete()
            messages.success(request, f"Your booking of {reservation_date} has been successfully canceled.")
        else:
            messages.warning(request, "Booking not found.")
        return redirect(self.success_url)


class BookingHistoryView(LoginRequiredMixin, generic.ListView):
    model = Reservation
    context_object_name = 'reservations'
    template_name = 'cozygames/booking_history.html'
    paginate_by = 12

    def get_queryset(self):
        return self.request.user.reservations.filter(date__lte=timezone.now().date()).order_by('-date')


class VotingView(generic.View):
    template_name = 'cozygames/voting.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        left_votes = 0
        if self.request.user.is_authenticated:
            left_votes = 3 - Vote.objects.filter(user=self.request.user, date=timezone.now().date()).count()

        last_voting = Voting.objects.filter(date=timezone.now().date() - timezone.timedelta(days=1)).first()
        game_of_day = None
        if last_voting:
            game_of_day = last_voting.result.name
        context = {
            'game_of_day': game_of_day,
            'form': VotingForm(),
            'left_votes': left_votes
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request: HttpRequest, *args, **kwargs):
        # schedule_tasks.update_voting.delay()
        form = VotingForm(request.POST)
        if form.is_valid():
            today_date = timezone.now().date()
            voting = get_object_or_404(Voting, date=today_date)
            card_game = get_object_or_404(CardGame, pk=form.cleaned_data['game'].id)

            if Vote.objects.filter(user=self.request.user, date=today_date).count() >= 3:
                messages.warning(request, "You cannot vote more than 3 times.")
            else:
                try:
                    Vote.objects.create(user=request.user, card_game=card_game, voting=voting)
                    messages.success(request, "Your vote has been recorded successfully.")
                except IntegrityError:
                    messages.warning(request, "You have already voted for this game.")

        return redirect(reverse_lazy('cozygames:voting'))


class CardGameInfoView(View):
    @method_decorator(cache_page(60 * 60 * 3))  # 3 hors
    def get(self, request, game_id):
        game = get_object_or_404(CardGame, pk=game_id)
        return render(request, 'cozygames/card_game_info.html', {'game': game})

    def post(self, request, game_id):
        return HttpResponseBadRequest("Invalid request")

cozygames/templates/cozygames/booking.html
{% extends 'base.html' %}
{% block title %}CozyGames: booking{% endblock %}
{% block body %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <h1 align="center">Booking your table</h1>
        </div>
        <div class="row-1 d-flex justify-content-center">
            <form action="{% url 'cozygames:booking' %}" method="POST" class="d-flex align-items-center">
                {% csrf_token %}
                <div style="margin-top: 20px;">
                    {{ form.as_p }}
                </div>
                <div style="margin-top: 0px; margin-left: 10px;">
                    <input type="submit" class="btn btn-primary custom-button" value="OK"/>
                </div>
            </form>
        </div>
        <div class="row-1 d-flex justify-content-center">
            <a href="{% url 'cozygames:cancel_bookings' %}">My reservation</a>
        </div>
        {% if tables %}
        <div class="row-1 d-flex justify-content-center">
            <h3>Available tables</h3>
        </div>
        <div class="row-1 d-flex justify-content-center">
            <div style="display: flex; flex-wrap: wrap;">
                {% for table in tables %}
                <div class="card m-2 bg-warning" style="width: 18rem;">
                    <div class="card-body" style="background-color: var(--card-body-bg-color);">
                        <h5 class="card-title text-center">Table {{ table.number }}</h5>
                        <p class="card-text text-center">
                            Type of table: {{ table.get_type_display }}<br>
                        </p>
                        <form action="{% url 'cozygames:booking_table' %}" method="POST" class="text-center">
                            {% csrf_token %}
                            <input type="hidden" name="table_id" value="{{ table.id }}">
                            <input type="hidden" name="date" value="{{ date|date:'Y-m-d' }}">
                            <input type="submit" value="Booking table" class="btn btn-primary custom-button">
                        </form>
                    </div>
                </div>

                {% endfor %}
            </div>
            {% else %}
            <div class="row-1 d-flex justify-content-center">
                <h3>No tables available</h3>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

cozygames/templates/cozygames/booking_history.html
{% extends 'base.html' %}
{% block title %}CozyGames: Booking history{% endblock %}
{% block body %}
<style>
    .page-link {
        background-color: #ffe1be;
        border-color: #dee2e6;
        color: #000;
    }
</style>
<div class="container">
    <div class="col-12">
        <div class="row">
            <h1 align="center">Your bookings history</h1>
        </div>
        <!-- Tiles of reservations -->
        <div class="row-1 d-flex justify-content-center">
            <div style="display: flex; flex-wrap: wrap;">
                {% if reservations %}
                {% for reservation in reservations %}
                <div class="card m-2 bg-warning" style="width: 18rem;">
                    <div class="card-body text-center" style="background-color: var(--card-body-bg-color);">
                        <h5 class="card-title">Table {{ reservation.table.number }}</h5>
                        <p class="card-text">
                            Type of table: {{ reservation.table.get_type_display }}<br>
                        </p>
                        <p class="card-text">Date: {{ reservation.date }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
        <!-- Pagination buttons -->
            <div class="mt-4">
                {% if is_paginated %}
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item"><span class="page-link" style="background-color: #41B3A3; color: #fff;">{{ num }}</span></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
            {% else %}
            <div class="row-1 d-flex justify-content-center">
                <h3>You don't have bookings yet.</h3>
            </div>
            {% endif %}
    </div>
</div>
{% endblock %}

cozygames/templates/cozygames/cancel_bookings.html
{% extends 'base.html' %}
{% block title %}CozyGames: Cancel booking{% endblock %}
{% block body %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <h1 align="center">Your active bookings</h1>
        </div>
        <!-- Tiles of reservations -->
        <div class="row-1 d-flex justify-content-center">
            <div style="display: flex; flex-wrap: wrap;">
                {% if reservations %}
                {% for reservation in reservations %}
                <div class="card m-2 bg-warning text-center" style="width: 18rem;">
                    <div class="card-body" style="background-color: var(--card-body-bg-color);">
                        <h5 class="card-title">Table {{ reservation.table.number }}</h5>
                        <p class="card-text">
                            Type of table: {{ reservation.table.get_type_display }}<br>
                        </p>
                        <p class="card-text">Date: {{ reservation.date }}</p>
                        <form action="{% url 'cozygames:cancel_bookings' %}" method="POST"
                              class="d-flex justify-content-center">
                            {% csrf_token %}
                            <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
                            <input type="submit" value="Cancel booking" class="btn btn-primary custom-button">
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- If not active reservations -->
            {% else %}
            <div class="row-1 d-flex justify-content-center">
                <h3>You don't have active bookings.</h3>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

cozygames/templates/cozygames/card_game_info.html
<div class="container">
    <hr>
    <div class="row justify-content-center">
        <div class="col-12">
            <h4 class="modal-title">{{ game.name }}</h4>
             <div class="row-6 d-flex justify-content-center">
                <div class="modal-body" style="text-align: justify;">
                    <p><b>Description:</b> {{ game.description }}</p>
                    <p><b>Minimum number of players:</b> {{ game.min_number_player }}</p>
                    <p><b>Maximum number of players:</b> {{ game.max_number_player }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

cozygames/templates/cozygames/index.html
{% extends 'base.html' %}
{% block body %}
<div style="color: #f00" align="center">
    <h1>Warning</h1>
    <ul style="color:ff4d00;">This site is a pet project. Do not write your real data here.</ul>
</div>
<div class="container">
    <div class="col-12">
        <div class="row">
            <h2 align="center">
                Schedule
            </h2>
            <ul>
                <li>Monday - Friday: 5:00 PM - 12:00 AM</li>
                <li>Saturday - Sunday: 12:00 PM - 12:00 AM</li>
            </ul>
        </div>
        <div class="row">
            <h2 align="center">Prices</h2>
            <ul>
                Single visit 5$ per person for the entire time spent in the club) and gives you the right to play
                all day, use the club's game library and get help from the staff.
                <li>10 visits: 45$</li>
                <li>20 visits: 90$</li>
                <li>1 month: 100$</li>
            </ul>
        </div>
        <div class="row">
            <h2 align="center">Can I come alone?</h2>
            <ul>
                Of course. You can always find someone to play with at the club, and many people make close friends
                here.
                Also, every week we have themed game nights. The theme is chosen by voting on the website. You can also
                take
                part in choosing the theme.
            </ul>
        </div>
    </div>
</div>
{% endblock %}

cozygames/templates/cozygames/voting.html
{% extends 'base.html' %}
{% block title %}CozyGames: Voting{% endblock %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="text-center">
            <h1>Game of the Day: {% if game_of_day %}{{ game_of_day }}{% else %}Any{% endif %}</h1>
        </div>

        <div class="col-12">
            <h2 class="text-center">Voting for the next day's game</h2>
            <div class="row-6 d-flex justify-content-center">
                Each day there is a vote for the game of the day. This game will be played tomorrow at the common table.
                Anyone can join the common table. Make your choice.
            </div>

            <div class="my-3"></div>
            {% if user.is_authenticated %}
            <div class="card mt-4 col-md-4 mx-auto" style="background-color: var(--card-body-bg-color);">
                <div class="card-body">
                    <div class="row-1 d-flex justify-content-center">
                        You have votes left today: {{ left_votes }}
                    </div>
                    <div class="row-1 d-flex justify-content-center">
                        <form id="votingForm" action="{% url 'cozygames:voting' %}" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="btn-group w-100" role="group" aria-label="Voting">
                                <button type="submit" class="btn btn-outline-primary w-50 mr-1 custom-button">Vote
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="row-1 d-flex justify-content-center">
                Login to vote!
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div id="gameInfo"></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
      $('#id_game').change(function() {
          var gameId = $(this).val();
          $.ajax({
              url: '/booking/card_game_info/' + gameId + '/',
              type: 'GET',
              success: function(response) {
                  $('#gameInfo').html(response);
              }
          });
      });
  });
</script>
{% endblock %}