cozygames_core/urls.py
from django.contrib import admin
from django.urls import path, include

from cozygames_core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cozygames.urls', namespace='booking')),
    path('users/', include('users.urls', namespace='user')),
    path('forum/', include('forum.urls', namespace='forum'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('themes/', views.ThemesView.as_view(), name='themes'),
    path('questions/<int:theme_id>', views.QuestionsView.as_view(), name='questions'),
    path('question_detail/<int:question_id>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('create_message/', views.CreateMessageView.as_view(), name='create_message'),
    path('create_question/', views.CreateQuestionView.as_view(), name='create_question'),

    path('client_reviews/', views.ClientReviewView.as_view(), name='client_reviews'),
    path('create_review/', views.CreateClientReviewView.as_view(), name='create_review'),

    path('blog/', views.BlogView.as_view(), name='blog'),

    path('tournaments/', views.TournamentsView.as_view(), name='tournaments'),
    path('tournament/<int:tournament_id>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('finished_tournaments/', views.FinishedTournamentsView.as_view(), name='finished_tournaments'),
    path('finished_tournament_detail/<int:tournament_id>/', views.FinishedTournamentDetailView.as_view(),
         name='finished_tournament_detail'),
    path('tournament/add/', views.AddParticipantView.as_view(), name='add_participant'),
    path('tournament/remove/', views.RemoveParticipantView.as_view(), name='remove_participant'),
    path('tournament/leave_tournament/', views.LeaveTournamentView.as_view(), name='leave_tournament'),
    path('tournament/create_tournament/', views.CreateTournamentView.as_view(), name='create_tournament'),
    path('tournament/my_tournaments/', views.MyTournamentsView.as_view(), name='my_tournaments'),
    path('tournament/participating_tournaments/', views.ParticipatingTournamentView.as_view(),
         name='participating_tournaments')
]

forum/forms.py
from django import forms
from django.utils import timezone

from . import models
from . import tasks

from django.contrib.admin import widgets
import datetime


class MessageForm(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = ['text', 'question']
        widgets = {
            'question': forms.HiddenInput(),
            'text': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Enter your message here...'})
        }
        auto_id = False

    def clean_text(self):
        text = self.cleaned_data['text']
        if not text.strip():  # Check if the text contains only spaces or an empty string
            raise forms.ValidationError("Message text cannot be empty.")
        return text


class CreateQuestionForm(forms.ModelForm):
    theme = forms.ModelChoiceField(queryset=models.Theme.objects.all(), label="Select theme",
                                   widget=forms.Select(attrs={'class': 'form-select magic-mint-focus'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control magic-mint-focus'}))
    text = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control magic-mint-focus', 'rows': 5, 'placeholder': 'Enter your question here...'}))

    class Meta:
        model = models.Question
        fields = ['title', 'text', 'theme']
        widgets = {
            'author': forms.HiddenInput(),
        }


class CreateReviewForm(forms.ModelForm):
    class Meta:
        RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]
        model = models.ClientReview
        fields = ('text', 'rating', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control magic-mint-focus', 'rows': 5,
                                          'placeholder': 'Enter your review here...'}),
            'rating': forms.Select(choices=RATING_CHOICES, attrs={'class': 'form-select magic-mint-focus'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control magic-mint-focus'}),
        }

    # def save(self, commit=True, *args, **kwargs):
    #     instance = super().save(*args, **kwargs)
    #     if instance.image and commit:
    #         tasks.create_thumbnail_image.delay(instance.__class__.__name__, instance.id, (75, 75))
    #
    #     return instance


class CreateTournamentForm(forms.ModelForm):
    class Meta:
        model = models.Tournament
        exclude = ('approved',)

        widgets = {
            'author': forms.HiddenInput(),
            'title': forms.TextInput(attrs={'class': 'form-control magic-mint-focus'}),
            'prize_pool': forms.TextInput(attrs={'class': 'form-control magic-mint-focus'}),
            'prize_distribution': forms.Textarea(attrs={'class': 'form-control magic-mint-focus', 'rows': 5,
                                                        'placeholder': 'Enter prize distribution...'}),
            'date': forms.DateTimeInput(attrs={'class': 'form-control magic-mint-focus', 'type': 'datetime-local'}),
            'max_players': forms.NumberInput(attrs={'class': 'form-control magic-mint-focus'}),
            'rules': forms.Textarea(attrs={'class': 'form-control magic-mint-focus', 'rows': 5,
                                           'placeholder': 'Enter tournament rules...'}),
            'type': forms.Select(attrs={'class': 'form-select magic-mint-focus'}),
        }

    def clean_date(self):
        date = self.cleaned_data.get('date')
        if date < timezone.now() + timezone.timedelta(days=3):
            raise forms.ValidationError("The tournament cannot start earlier than 3 days from now.")

        if date.time() < datetime.time(10, 0) or date.time() > datetime.time(18, 0):
            raise forms.ValidationError("The time should be between 10:00 and 18:00.")

        if self.cleaned_data.get('title'):
            raise forms.ValidationError("The title can't be empty.")

        if self.cleaned_data.get('prize_pool'):
            raise forms.ValidationError("The prize pool can't be empty.")

        return date

forum/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page

from . import forms, tasks, models


class ThemesView(generic.ListView):
    model = models.Theme
    template_name = 'forum/themes.html'
    context_object_name = 'themes'


class QuestionsView(generic.ListView):
    model = models.Question
    template_name = 'forum/questions.html'
    context_object_name = 'questions'

    def get_queryset(self):
        theme_id = self.kwargs.get('theme_id')
        if theme_id:
            return self.model.objects.filter(theme__id=theme_id)
        return [self.model.objects.first()]


class QuestionDetail(generic.DetailView):
    model = models.Question
    template_name = 'forum/question_detail.html'
    context_object_name = 'question'
    pk_url_kwarg = 'question_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_messages'] = context['question'].messages.all()
        context['form'] = forms.MessageForm()
        return context


class CreateMessageView(LoginRequiredMixin, generic.FormView):
    template_name = 'forum/question_detail.html'
    form_class = forms.MessageForm

    def form_valid(self, form):
        message = form.save(commit=False)
        message.question = form.cleaned_data['question']
        message.user = self.request.user
        message.save()
        return redirect(reverse('forum:question_detail', kwargs={'question_id': form.cleaned_data['question'].pk}))

    def form_invalid(self, form):
        messages.warning(self.request, "You are trying to send the wrong message.")
        return super().form_invalid(form)


class CreateQuestionView(LoginRequiredMixin, generic.FormView):
    template_name = 'forum/create_question.html'
    form_class = forms.CreateQuestionForm

    def form_valid(self, form: forms.forms.ModelForm):
        question = form.save(commit=False)
        question.author = self.request.user
        question.theme = form.cleaned_data['theme']
        question.save()
        return redirect(reverse('forum:questions', kwargs={'theme_id': form.cleaned_data['theme'].id}))

    def form_invalid(self, form):
        messages.warning(self.request, "Incorrect input.")
        return super().form_invalid(form)


class ClientReviewView(generic.ListView):
    model = models.ClientReview
    ordering = ('-date_posted',)
    context_object_name = 'client_reviews'
    queryset = model.objects.filter(approved=True)
    template_name = 'forum/client_reviews.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = forms.CreateReviewForm()
        return context


class CreateClientReviewView(generic.FormView):
    template_name = 'forum/client_reviews.html'
    form_class = forms.CreateReviewForm

    def form_valid(self, form: forms.CreateReviewForm):
        review = form.save(commit=False)
        if self.request.user.is_authenticated:
            review.user = self.request.user
        else:
            review.user = None
        review.save()
        tasks.create_thumbnail_image.delay(review.__class__.__name__, review.id, (75, 75))
        return redirect(reverse('forum:client_reviews'))


class BlogView(generic.ListView):
    model = models.Article
    ordering = ('-date_posted', '-pk')
    context_object_name = 'articles'
    template_name = 'forum/articles.html'
    paginate_by = 10
    queryset = model.objects.all().prefetch_related('images')


class TournamentsView(generic.ListView):
    model = models.Tournament
    ordering = ('-date', '-pk')
    context_object_name = 'tournaments'
    template_name = 'forum/tournaments.html'

    def get_queryset(self):
        return self.model.objects.filter(date__gte=timezone.now(), approved=True).all()


class FinishedTournamentsView(generic.ListView):
    model = models.Tournament
    ordering = ('-date', '-pk')
    context_object_name = 'tournaments'
    template_name = 'forum/finished_tournaments.html'

    @classmethod
    def as_view(cls):
        view = super().as_view()
        return cache_page(60 * 60 * 1)(view)  # Cache the page for 3 hours

    def get_queryset(self):
        return self.model.objects.filter(date__lte=timezone.now(), approved=True).all()


class TournamentDetailView(generic.DetailView):
    model = models.Tournament
    template_name = 'forum/tournament_detail.html'
    context_object_name = 'tournament'
    pk_url_kwarg = 'tournament_id'

    def get_queryset(self):
        return super().get_queryset().prefetch_related(
            Prefetch('participants', queryset=models.TournamentParticipant.objects.select_related('user'))
        )


class FinishedTournamentDetailView(generic.DetailView):
    model = models.Tournament
    template_name = 'forum/finished_tournament_detail.html'
    context_object_name = 'tournament'
    pk_url_kwarg = 'tournament_id'

    @classmethod
    def as_view(cls):
        view = super().as_view()
        return cache_page(60 * 60 * 3)(view)  # Cache the page for 3 hours

    def get_queryset(self):
        return super().get_queryset().prefetch_related(
            Prefetch('winners', queryset=models.TournamentWinner.objects.select_related('user')),
            Prefetch('participants', queryset=models.TournamentParticipant.objects.select_related('user'))
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            if models.TournamentParticipant.objects.filter(tournament=self.kwargs.get('tournament_id'),
                                                           user=self.request.user).first():
                context['user_is_joined'] = True
        return context

    @method_decorator(login_required)
    def post(self, *args, **kwargs):
        tournament: models.Tournament = self.model.objects.filter(pk=self.request.POST.get('tournament_id', 0)).first()

        if not tournament:
            messages.warning(self.request, 'This tournament non exists')

        elif timezone.now() > tournament.date:
            messages.warning(self.request, "You can't join to finished the tournament.")

        elif models.TournamentParticipant.objects.filter(user=self.request.user, tournament=tournament):
            messages.warning(self.request, "You have already submitted")

        else:
            tournament_participant = models.TournamentParticipant(user=self.request.user, tournament=tournament)
            if tournament.type == models.Tournament.Type.OPEN:
                tournament_participant.status = models.TournamentParticipant.Status.APPROVED
                messages.success(self.request, "You have joined the tournament.")
            else:
                messages.success(self.request, "Your application has been accepted.")
            tournament_participant.save()

        return redirect(
            reverse('forum:tournament_detail', args=(tournament.pk,))) if tournament else (
            redirect('forum:tournaments'))


class AddParticipantView(LoginRequiredMixin, generic.View):
    model = models.Tournament

    def post(self, *args, **kwargs):
        tournament = get_object_or_404(self.model, pk=self.request.POST.get('tournament_id', 0))

        if self.request.user == tournament.author:
            participant: models.TournamentParticipant = get_object_or_404(models.TournamentParticipant,
                                                                          pk=self.request.POST.get('participant_id', 0))
            if tournament.participants.count() < tournament.max_players:
                participant.status = models.TournamentParticipant.Status.APPROVED
                participant.save()
                messages.success(self.request, f"{participant.user.username} has been successfully added to "
                                               f"the list of participants.")
            else:
                messages.warning(self.request,
                                 f"{participant.user.username} was not added. Maximum number of players reached"
                                 f" in the tournament.")

        return redirect(reverse('forum:tournament_detail', args=(tournament.pk,)))


class RemoveParticipantView(LoginRequiredMixin, generic.View):
    model = models.Tournament

    def post(self, *args, **kwargs):
        tournament = get_object_or_404(self.model, pk=self.request.POST.get('tournament_id', 0))

        if self.request.user == tournament.author:
            participant: models.TournamentParticipant = get_object_or_404(models.TournamentParticipant,
                                                                          pk=self.request.POST.get('participant_id', 0))

            if tournament.type == self.model.Type.OPEN:
                participant.delete()
            elif tournament.type == models.Tournament.Type.CLOSED:
                participant.status = models.TournamentParticipant.Status.PENDING
                participant.save()

            messages.success(self.request,
                             f"{participant.user.username} has been successfully excluded from the list of "
                             f"participants.")

        return redirect(reverse('forum:tournament_detail', args=(tournament.pk,)))


class LeaveTournamentView(LoginRequiredMixin, generic.View):
    def post(self, *args, **kwargs):
        tournament = get_object_or_404(models.Tournament, pk=self.request.POST.get('tournament_id', 0))

forum/templates/forum/client_reviews.html
{% extends 'base.html' %}
{% block title %}Cozygames: Client Reviews{% endblock %}
{% block body %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div style="background-color: var(--card-body-bg-color);">
                    <div class="card-body">
                        <h2 class="card-title text-center">Client Reviews</h2>
                        <hr>
                        {% for review in client_reviews %}
                        <div class="card mb-3">

                            <div class="card-body">
                                <p class="card-text">{{ review.text }}</p>
                                <p class="card-text"><small class="text-muted">Rating: {{ review.rating }}</small></p>
                                {% if review.image %}
                                <a href="#" data-bs-toggle="modal" data-bs-target="#image_modal_{{ review.id }}">
                                    <img src="{{ review.get_thumbnail_url }}" class="card-img-top img-thumbnail"
                                         alt="Review Photo" style="width: 75px; height: 75px;">
                                </a>
                                <!-- Modal -->
                                <div class="modal fade" id="image_modal_{{ review.id }}" tabindex="-1"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-xl">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <img src="{{ review.get_photo_url }}" class="img-fluid"
                                                     alt="Review Photo">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                <p class="card-text"><small class="text-muted">Posted by
                                    {% if review.user.username %} {{ review.user.username }}
                                    {% else %} anonymous {% endif %}
                                    on {{ review.date_posted }}</small></p>
                            </div>
                        </div>
                        {% empty %}
                        <p>No client reviews yet.</p>
                        {% endfor %}
                    </div>

                    <!-- Pagination buttons -->
                    <div class="mt-4">
                        {% if is_paginated %}
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <li class="page-item"><span class="page-link"
                                                        style="background-color: var(--hover-button-color); color: #fff;">{{ num }}</span>
                            </li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div style="background-color: #ffe1be;">
                    <div class="card-body">
                        <h2 class="card-title text-center">Leave feedback</h2>
                        <hr>

                        <!-- Form to submit a new review -->
                        <form action="{% url 'forum:create_review' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary w-100 custom-button" data-toggle="modal"
                                    data-target="#profileModal">Submit Review
                            </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    /* Styles for highlighting Magic Mint color when in focus */
    .magic-mint-focus:focus {
        box-shadow: 0 0 5px #AAF0D1;
    }
</style>
{% endblock %}

forum/templates/forum/tournament_detail.html
{% extends 'base.html' %}
{% block title %}CozyGames: Tournament {% endblock %}
{% block body %}
{% if tournament.approved %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header" style="background-color: var(--card-body-bg-color);">
                    <h2 class="card-title text-center">{{ tournament.title }}</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Type:</strong> {{ tournament.get_type_display }}</li>
                        <li class="list-group-item"><strong>Prize Pool:</strong> {{ tournament.prize_pool }}</li>
                        <li class="list-group-item"><strong>Prize Distribution:</strong>
                            {{ tournament.prize_distribution|linebreaks }}
                        <li class="list-group-item"><strong>Date of Holding:</strong> {{ tournament.date }}</li>
                        <li class="list-group-item"><strong>Max Players:</strong> {{ tournament.max_players }}</li>
                        <li class="list-group-item"><strong>Rules:</strong> {{ tournament.rules }}</li>
                    </ul>
                    {% if user_is_joined %}
                    <form action="{% url 'forum:leave_tournament' %}" method="post"
                          class="d-flex align-items-center">
                        {% csrf_token %}
                        <input type="hidden" name="tournament_id" value="{{ tournament.pk }}">
                        <button type="submit" class="btn btn-primary w-100">Leave</button>
                    </form>
                    {% else %}
                    <form action="{% url 'forum:tournament_detail' tournament.id %}" method="post"
                          class="d-flex align-items-center">
                        {% csrf_token %}
                        <input type="hidden" name="tournament_id" value="{{ tournament.pk }}">
                        <button type="submit" class="btn btn-primary w-100 custom-button">Join</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header" style="background-color: var(--card-body-bg-color);">
                    <h2 class="card-title text-center">List of participants in the tournament</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for participant in tournament.participants.all %}
                        {% if participant.status == 'A' %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {% if user == tournament.author %}
                            <div>{{ participant.user.username }}</div>
                            <form method="post" action="{% url 'forum:remove_participant' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{ participant.pk }}" name="participant_id">
                                <input type="hidden" value="{{ tournament.pk }}" name="tournament_id">
                                <button type="submit" class="btn btn-danger custom-danger-button">Remove</button>
                            </form>
                            {% else %}
                            <div class="text-center w-100">{{ participant.user.username }}</div>
                            {% endif %}
                        </li>
                        {% endif %}
                        {% empty %}
                        <li class="list-group-item text-center">No one has joined yet</li>
                        {% endfor %}
                    </ul>


                </div>
            </div>
        </div>
    </div>
</div>

{% if tournament.type == 'CL' %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header" style="background-color: var(--card-body-bg-color);">
                    <h2 class="card-title text-center">Wish to be joined</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush text-center">
                        {% for participant in tournament.participants.all %}
                        {% if participant.status == 'P' %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {% if user == tournament.author %}
                            <div>{{ participant.user.username }}</div>
                            <form method="post" action="{% url 'forum:add_participant' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{ participant.pk }}" name="participant_id">
                                <input type="hidden" value="{{ tournament.id }}" name="tournament_id">
                                <button type="submit" class="btn btn-success custom-button">Add</button>
                            </form>
                            {% else %}
                            <div class="text-center w-100">{{ participant.user.username }}</div>
                            {% endif %}
                            {% endif %}
                            {% empty %}
                        <li class="list-group list-group-flush text-center">No one wish to be joined yet</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% else %}
<h1 class="text-center">This is not approved tournament</h1>
{% endif %}
{% endblock %}

forum/templates/forum/tournaments.html
{% extends 'base.html' %}
{% block title %}CozyGames: Tournaments{% endblock %}
{% block body %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h1 class="text-center">Tournaments</h1>
            <div class="card mt-4" style="background-color: #ffe1be;">
                <div class="card-body">
                    <p>
                        Welcome to our tournaments page! Here you can participate in exciting competitions of tabletop
                        games or create your own tournament. We offer various types of tournaments, including open and
                        closed ones.
                    </p>
                    <p>
                        <strong>Open Tournaments:</strong> Anyone interested can join open tournaments without any
                        restrictions. Simply choose the tournament you're interested in and apply to participate!
                    </p>
                    <p>
                        <strong>Closed Tournaments:</strong> Some tournaments may be available by invitation only or
                        after confirmation by the creator. If you have an invitation or want to create your own closed
                        tournament, please contact the site administrator or create your tournament with the appropriate
                        settings.
                    </p>
                    <p>
                        Remember that participation in tournaments implies adherence to the general rules of conducting
                        competitions:
                    </p>
                    <ol>
                        <li><strong>Respect Others:</strong> Treat fellow participants with kindness and respect. Avoid
                            insults, discrimination, or any other form of intolerance.
                        </li>
                        <li><strong>Be Civil and Constructive:</strong> Maintain polite and constructive dialogue.
                            Disagreements are normal, but express your viewpoints respectfully, without hostility or
                            insults.
                        </li>
                    </ol>
                </div>
            </div>
            <a href="{% url 'forum:create_tournament' %}" class="create-question-link">Create own tournament</a>
            <a href="{% url 'forum:finished_tournaments' %}" class="create-question-link">Finished tournaments</a>
            <!-- List of active tournaments -->
            <div class="list-group mt-3">
                {% for tournament in tournaments %}
                <a href="{% url 'forum:tournament_detail' tournament.id %}"
                   class="list-group-item list-group-item-action"
                   style="background-color: {% cycle '#ffefd5;' '#ffe1be;' %}">
                    <div class="d-flex justify-content-between">
                        <span>{{ tournament.title }}</span>
                        <span>{{ tournament.date }}</span>
                    </div>
                </a>
                {% empty %}
                <h3 class="text-center">There are no tournaments scheduled yet. You can create your own</h3>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}