cozygames/urls.py
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'cozygames'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('booking_table/', views.BookingTableView.as_view(), name='booking_table'),
    path('booking/cancel_bookings/', views.CancelReservation.as_view(), name='cancel_bookings'),
    path('booking/booking_history/', views.BookingHistoryView.as_view(), name='booking_history'),
    path('booking/voting/', views.VotingView.as_view(), name='voting'),
    path('booking/card_game_info/<int:game_id>/', views.CardGameInfoView.as_view(), name='card_game_info'),
]

cozygames_core/urls.py
from django.contrib import admin
from django.urls import path, include

from cozygames_core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cozygames.urls', namespace='booking')),
    path('users/', include('users.urls', namespace='user')),
    path('forum/', include('forum.urls', namespace='forum'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('themes/', views.ThemesView.as_view(), name='themes'),
    path('questions/<int:theme_id>', views.QuestionsView.as_view(), name='questions'),
    path('question_detail/<int:question_id>/', views.QuestionDetail.as_view(), name='question_detail'),
    path('create_message/', views.CreateMessageView.as_view(), name='create_message'),
    path('create_question/', views.CreateQuestionView.as_view(), name='create_question'),

    path('client_reviews/', views.ClientReviewView.as_view(), name='client_reviews'),
    path('create_review/', views.CreateClientReviewView.as_view(), name='create_review'),

    path('blog/', views.BlogView.as_view(), name='blog'),

    path('tournaments/', views.TournamentsView.as_view(), name='tournaments'),
    path('tournament/<int:tournament_id>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('finished_tournaments/', views.FinishedTournamentsView.as_view(), name='finished_tournaments'),
    path('finished_tournament_detail/<int:tournament_id>/', views.FinishedTournamentDetailView.as_view(),
         name='finished_tournament_detail'),
    path('tournament/add/', views.AddParticipantView.as_view(), name='add_participant'),
    path('tournament/remove/', views.RemoveParticipantView.as_view(), name='remove_participant'),
    path('tournament/leave_tournament/', views.LeaveTournamentView.as_view(), name='leave_tournament'),
    path('tournament/create_tournament/', views.CreateTournamentView.as_view(), name='create_tournament'),
    path('tournament/my_tournaments/', views.MyTournamentsView.as_view(), name='my_tournaments'),
    path('tournament/participating_tournaments/', views.ParticipatingTournamentView.as_view(),
         name='participating_tournaments')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.RegisterUser.as_view(), name='registration'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

users/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import QuerySet


# Create your models here.
class Profile(models.Model):
    user: User = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateTimeField(blank=True, null=True)
    phone_regex = RegexValidator(
        regex=r'^\+375(24|25|29|33|44)\d{7}$',
        message="Phone number should start with +375 and consist of 13 digits. For exemple +375291231212 "
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=13, blank=True)  # Validators should be a list
    objects: QuerySet

    def __str__(self):
        return f"Profile: {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from users.models import Profile


class ReceiverForm(forms.ModelForm):
    phone_number = forms.RegexField(regex=r'^\+375(24|25|29|33|44)\d{7}$', error_messages={
        'invalid': "Phone number should start with +375 and consist of 13 digits. For exemple +375291231212 ", })


class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'})
        }

    def clean_email(self):
        """ Duplicate email verification or field is empty"""
        email = self.cleaned_data['email']
        if not email:
            raise forms.ValidationError("This field is required.")
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
        return email


class LoginUserForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, 'class': 'form-control'}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", 'class': 'form-control'}),
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': "First name",
            'last_name': "Last name",
            'username': "Username",
            'email': "Email"
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'})
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birthday', 'phone_number']
        labels = {
            'birthday': "Birthday",
            'phone_number': "Phone Number"
        }
        widgets = {
            'birthday': forms.DateInput(attrs={'class': 'form-input', 'type': 'date', 'max': timezone.now().date()}),
            'phone_number': forms.TextInput(attrs={'class': 'form-input'})
        }

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views import generic

from users.forms import CreateUserForm, LoginUserForm, UserForm, ProfileForm
from users.models import Profile


# Create your views here.
class RegisterUser(CreateView):
    form_class = CreateUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        next_url = self.request.GET.get('next')
        if next_url:
            return HttpResponseRedirect(next_url)
        return response


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'


class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'user_form' not in context:
            context['user_form'] = UserForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        user_form = UserForm(self.request.POST, instance=self.request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(self.request, "Your profile has been updated successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('user:profile')

users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}CozyGames: sign in{% endblock %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <h2 class="text-center">Login</h2>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">

                {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    <div style="color: var(--error-text-color)">{{ field.errors }}</div>
                </div>
                {% endfor %}

                {% if form.non_field_errors %}
                <div style="color: var(--error-text-color)">
                    <ul class='form-errors'>
                        {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                <div class="mb-3 d-grid">
                    <button type="submit" class="btn btn-primary custom-button">Sign up</button>
                </div>
            </form>
            <a href="{% url 'users:registration' %}?next={{ next }}">Create new account</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}CozyGames: Profile{% endblock %}
{% block body %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <h1 class="text-center">Your profile, {{ user.username }}</h1>
        </div>

        <div class="row-1 d-flex justify-content-center">
            <div style="display: flex; flex-wrap: wrap;">
                <div class="card m-2 bg-warning">
                    <div class="card-body" style="background-color: var(--card-body-bg-color);">
                        <div class="row justify-content-center mb-2">
                            <a class="btn btn-primary custom-button"
                               href="{% url 'cozygames:cancel_bookings' %}">My reservation</a>
                        </div>
                        <div class="row justify-content-center mb-2">
                            <a class="btn btn-primary custom-button"
                               href="{% url 'cozygames:booking_history' %}">Booking history</a>
                        </div>
                        <div class="row justify-content-center mb-2">
                            <a class="btn btn-primary custom-button"
                               href="{% url 'forum:my_tournaments' %}">My tournaments</a>
                        </div>
                        <div class="row justify-content-center">
                            <a class="btn btn-primary custom-button"
                               href="{% url 'forum:participating_tournaments' %}">Participating Tournaments</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="row-1 d-flex justify-content-center">
            <div style="display: flex; flex-wrap: wrap;">
                <div class="card m-2 bg-warning">
                    <div class="card-body" style="background-color: var(--card-body-bg-color);">
                        <h5 class="card-title">Change your personal data</h5>
                        <form action="{% url 'users:profile' %}" method="POST">
                            {% csrf_token %}
                            {% for field in user_form %}
                            <div class="mb-3 d-block">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                <br>
                                {{ field }}
                                <div style="color: var(--error-text-color)">{{ field.errors }}</div>
                            </div>
                            {% endfor %}
                            {% for field in form %}
                            <div class="mb-3 d-block">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                <br>
                                {{ field }}
                                <div style="color: var(--error-text-color)">{{ field.errors }}</div>
                            </div>
                            {% endfor %}
                            <input type="submit" value="Change" class="btn btn-outline-primary w-100 custom-button"
                                   data-toggle="modal" data-target="#profileModal">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block title %}CozyGames: sign up{% endblock %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <h2 class="text-center">Registration</h2>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    <div style="color: var(--error-text-color)">{{ field.errors }}</div>
                </div>
                {% endfor %}
                <div class="mb-3 d-grid">
                    <button type="submit" class="btn btn-primary custom-button">Sign up</button>
                </div>
            </form>
            <a href="{% url 'users:login' %}?next={{ next }}">Are you already have an account? Sign in</a>
        </div>
    </div>
</div>
{% endblock %}